In [9]:
from sklearn import svm
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn import datasets

iris = datasets.load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size= 0.3)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
svm_model = svm.SVC(kernel='linear', C=1)
svm_model.fit(X_train, y_train)
print(svm_model.score(X_test, y_test))

(105, 4) (105,)
(45, 4) (45,)
0.9555555555555556


In [12]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

Xd_train, Xd_test, yd_train, yd_test = train_test_split(iris.data, iris.target, test_size= 0.3)

svm_reg= SVR(gamma = "auto")
svm_reg= svm_reg.fit(Xd_train, yd_train)
pred_svm= svm_reg.predict(Xd_test)
print("Valoresprevistos: " , pred_svm)
mse= mean_squared_error(yd_test, pred_svm)
print("MSE: %.1f" % mse)

Valoresprevistos:  [ 0.00342676  1.12701388  0.98300786  1.05359458  0.01600813 -0.01351355
  1.87995307  1.74600218  2.07120194  0.85422848  1.0918266   1.07238754
  1.65809935  0.10715552  1.22257786  2.01187512  0.02306888  0.00387712
  0.01403105  0.95281961  0.98544378  1.94453828  0.00716746 -0.01111469
  1.2924811   2.05998049  0.05520811  1.20464974 -0.01904586  0.05885082
  0.08782253  2.02837543  1.93139007  0.0585821   1.94983317  1.53270328
  1.90290296  0.91530169  1.17903485  1.56787188  1.30019035  0.8248995
  1.78535036  2.04390369  0.02886761]
MSE: 0.0


In [22]:
from sklearn import datasets, svm
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import cross_val_score

digits = datasets.load_digits()
print (digits.data.shape)
sel= VarianceThreshold(threshold=20)
filt= sel.fit_transform(digits.data)
print (filt.shape)
print(filt)
svm_model= svm.SVC(gamma=0.001, C=100.)
scores= cross_val_score(svm_model, digits.data, digits.target, cv= 10)
print (scores.mean())
scores_vt= cross_val_score(svm_model, filt, digits.target, cv= 10)
print (scores_vt.mean())

(1797, 64)
(1797, 29)
[[ 5.  1. 13. ...  6. 10.  0.]
 [ 0.  5.  0. ...  0. 16. 10.]
 [ 0. 12.  3. ...  0. 11. 16.]
 ...
 [ 1.  1. 13. ...  2. 13.  6.]
 [ 2.  0. 14. ...  5. 16. 12.]
 [10.  1. 16. ...  8. 14. 12.]]
0.9810738671632526
0.9777405338299193


In [15]:
from sklearn.feature_selection import RFE
svm_model= svm.SVC(kernel = "linear", C=100.)
rfe= RFE(estimator=svm_model, n_features_to_select=32, step=1)
scores_rfe= cross_val_score(rfe, digits.data, digits.target, cv = 10)
print (scores_rfe.mean())

0.9499224084419614


In [24]:
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score, GridSearchCV

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 3, 10, 100], 'gamma':[0.01, 0.001]}
svm_model_d= svm.SVC()
opt_model_d= GridSearchCV(svm_model_d, parameters)
opt_model_d.fit(digits.data, digits.target)
print (opt_model_d.best_estimator_)
scores_gs= cross_val_score(opt_model_d, digits.data, digits.target, cv = 5)
print (scores_gs.mean())

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
0.972185082017951


In [30]:
import numpy as np
def report(results, n_top=3):
    for i in range(1, n_top+ 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                results['mean_test_score'][candidate],
                results['std_test_score'][candidate]))
        print("Parameters: {0}".format(results['params'][candidate]))
        print("")

In [31]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

rf_model= RandomForestClassifier(n_estimators=100)
param_dist= {"max_depth": [2, 3, None], "max_features": [2,4,6], "min_samples_split": [2,4,6], "min_samples_leaf": [2,4,6], "bootstrap": [True, False], "criterion": ["gini", "entropy"]}
rand_search= RandomizedSearchCV(rf_model, param_distributions=param_dist, n_iter=20, cv = 5)
rand_search.fit(digits.data, digits.target)
print (rand_search.best_estimator_)
report(rand_search.cv_results_)
scores_rs= cross_val_score(rand_search, digits.data, digits.target, cv = 5)
print (scores_rs.mean())

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
Model with rank: 1
Mean validation score: 0.927 (std: 0.021)
Parameters: {'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 2, 'max_depth': None, 'criterion': 'entropy', 'bootstrap': True}

Model with rank: 2
Mean validation score: 0.927 (std: 0.018)
Parameters: {'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 2, 'max_depth': None, 'criterion': 'gini', 'bootstrap': True}

Model with rank: 3
Mean validation score: 0.927 (std